
```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# Introduction



  
## Motivation


## Target Audience  

This course is intended for people conducting data analyses at the level of a graduate student or higher. The course is designed so that the majority of the material is presented in a high-level manner that should be applicable to researchers working in a broad range of areas. The course is centered around the R programming language, a widely used statistical analysis software package. 

## Curriculum  

The course covers...


## Learning Objectives

- Implement basic project organization tools:
   - Setup and configure RStudio/RStudio projects for data analysis (`here` package and file structure/paths)
   - Install and configure `ProjectTemplate` package for formalizing and automating workflows
- Apply the `pointblank` package for validation of tabular data 
- Write functions and package them
- Apply the `testthat` package for building software unit tests
- Setup and use Git repositories for version control of code 
- Interface with GitHub to share Git repositories for collaboration; execute GitHub-based workflows 
  - Pull Requests
  - Code review
  - Issues
  - Discussions
  
References will include @gillespie_efficient_2021, @riederer_column_2020, @timbers_data_nodate.

Code review references will include @hutchdatascience_code_review, @radigan_what_nodate, @parker_opinionated_2017, @bodner_10_2018.
