
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://www.ottrproject.org/more_features.html#giving-credits-to-contributors).

&nbsp;
&nbsp;

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor(s)|[Carrie Wright], [Candace Savonen]|
|Content Author(s)| [Candace Savonen], [Carrie Wright]|
|Content Director(s)| [Roger Peng]|
|Acknowledgments| Some of this material was repurposed from the [ITCR Training Network](https://www.itcrtraining.org/)|
|**Production**||
|Content Publisher(s)| [Candace Savonen], [Carrie Wright]|
|**Technical**||
|Course Publishing Engineer(s)| [Candace Savonen], [Carrie Wright]|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Candace Savonen]|
|Package Developers ([ottrpal]) [Candace Savonen], [John Muschelli], [Carrie Wright]|
|**Art and Design**||
|Illustrator(s)| [Carrie Wright][Candace Savonen]|
|**Funding**||
|Funder(s)| This work was funded by the NIH, grant number [5R25GM141505](https://reporter.nih.gov/search/k_pXzn8wfUeEvaWpnzIToA/project-details/10663171)|
|Funding Staff| [Maleah O'Connor](https://www.linkedin.com/in/maleah-o-connor)|

&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->

[FirstName LastName]: link to personal website
[John Muschelli]: https://johnmuschelli.com/
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/
[Roger Peng]: https://rdpeng.org/
<!-- Links -->

[ottrpal]: https://github.com/jhudsl/ottrpal

<!-- Fill out this table using these instructions: https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits

For JHU courses, You will need to add Ira as a credit:

|Content Publisher|[Ira Gooding]|
...
[Ira Gooding]: https://publichealth.jhu.edu/faculty/4130/ira-gooding
-->
